//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public string tracker_id { get; set; }
        public string name { get; set; }
        public int owner_id { get; set; }
        public int last_updater { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime last_update { get; set; }
    }
}
