//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime begin { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<int> user_id { get; set; }
        public long project_id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Users Users { get; set; }
    }
}
