//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationManagementServices.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChangeSet()
        {
            this.ChangeSet1 = new HashSet<ChangeSet>();
        }
    
        public string shortName { get; set; }
        public string description { get; set; }
        public int addition { get; set; }
        public int deletion { get; set; }
        public int edition { get; set; }
        public string trackerId { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> parent { get; set; }
        public int origin { get; set; }
        public System.DateTime stamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeSet> ChangeSet1 { get; set; }
        public virtual ChangeSet ChangeSet2 { get; set; }
        public virtual File File { get; set; }
        public virtual Users Users { get; set; }
    }
}
