//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationDatabaseMaintenanceService.DAL.Token
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public string jni { get; set; }
        public string token1 { get; set; }
        public string t_key { get; set; }
        public System.DateTime exp { get; set; }
        public System.DateTime beg { get; set; }
        public string boundmac { get; set; }
    }
}
